version: "3.9"

services:
  apache:
    build: ./apache
    container_name: apache
    depends_on:
      cobol-server:
        condition: service_healthy
      mysql:
        condition: service_started
    volumes:
      - ./frontend:/usr/local/apache2/htdocs:ro
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - cobol_socket:/var/run/cobol
    ports:
      - "3000:80"
    environment:
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}


  cobol-server:
    build: ./cobol
    container_name: cobol-server
    volumes:
      - cobol_socket:/var/run/cobol
    healthcheck:
      test: ["CMD", "test", "-S", "/var/run/cobol/cobol.sock"]
      interval: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

volumes:
  db_data:
  cobol_socket: