version: "3"

tasks:
  clean:
    desc: "全サービスの停止と削除（ボリュームやイメージは残す）"
    cmds:
      - docker compose down

  fclean:
    desc: "全サービスの完全初期化（ボリューム・イメージも削除）"
    cmds:
      - |
        read -p "Are you sure you want to fully reset everything? [y/N] " confirm && \
        [ "$confirm" = "y" ] && docker compose down -v --rmi all --remove-orphans

  re:
    desc: "全サービスのリセットと再ビルド（clean → build）"
    cmds:
      - task clean
      - task build
      - task start

  build:
    desc: "全サービスをビルド"
    deps: [build:apache, build:cobol, build:postgre]

  re:mod:
    desc: "Apacheコンテナ内で mod_cobol_server を再ビルド＆再インストール"
    cmds:
      - docker exec -w /usr/local/src apache make clean || true
      - docker exec -w /usr/local/src apache make
      - docker exec -w /usr/local/src apache make install
      - docker exec apache apachectl -k graceful

  start:
    desc: "全サービスを起動"
    deps: [start:apache, start:cobol, start:postgre]

  logs:
    desc: "すべてのサービスのログを表示"
    cmds:
      - docker compose logs -f

  default:
    silent: true
    cmds:
      - task --list
      - |
        sh -c '
        green="\033[0;32m"
        red="\033[0;31m"
        yellow="\033[0;33m"
        magenta="\033[0;35m"
        reset="\033[0m"
        echo "${yellow}*${reset} ${green}task${reset}:${magenta}service${reset}  所定のserviceのみ起動 ${magenta}apache / cobol / postgre${reset} "
        echo ""
        '

  # === apache ===
  build:apache:
    cmds:
      - docker compose build apache
    ignore_error: true

  start:apache:
    cmds:
      - docker compose up -d apache
    ignore_error: true

  re:apache:
    deps: [build:apache, start:apache]

  logs:apache:
    cmds:
      - docker compose logs -f apache

  # === cobol ===
  build:cobol:
    cmds:
      - docker compose build cobol-server
    ignore_error: true

  start:cobol:
    cmds:
      - docker compose up -d cobol-server
    ignore_error: true

  re:cobol:
    deps: [build:cobol, start:cobol]

  logs:cobol:
    cmds:
      - docker compose logs -f cobol-server

  # === postgre ===
  build:postgre:
    cmds:
      - echo "postgre uses image; no build needed"
    ignore_error: true

  start:postgre:
    cmds:
      - docker compose up -d postgre
    ignore_error: true

  re:postgre:
    deps: [start:postgre]

  logs:postgre:
    cmds:
      - docker compose logs -f postgre
