version: "3"

tasks:
  clean:
    desc: "全サービスの停止と削除（ボリュームやイメージは残す）"
    cmds:
      - docker compose down

  fclean:
    desc: "全サービスの完全初期化（ボリューム・イメージも削除）"
    cmds:
      - |
        read -p "Are you sure you want to fully reset everything? [y/N] " confirm && \
        [ "$confirm" = "y" ] && docker compose down -v --rmi all --remove-orphans

  re:
    desc: "全サービスのリセットと再ビルド（clean → build）"
    cmds:
      - task clean
      - task build
      - task start

  build:
    desc: "全サービスをビルド"
    deps: [build:apache, build:cobol, build:mysql]

  start:
    desc: "全サービスを起動"
    deps: [start:apache, start:cobol, start:mysql]

  default:
    silent: true
    cmds:
      - task --list
      - |
        sh -c '
        green="\033[0;32m"
        red="\033[0;31m"
        yellow="\033[0;33m"
        magenta="\033[0;35m"
        reset="\033[0m"
        echo "${yellow}*${reset} ${green}task${reset}:${magenta}service${reset}  所定のserviceのみ起動 ${magenta}apache / cobol / mysql${reset} "
        echo ""
        '

  # === apache ===
  build:apache:
    cmds:
      - docker compose build apache

  start:apache:
    cmds:
      - docker compose up -d apache

  re:apache:
    deps: [build:apache, start:apache]

  # === cobol ===

  build:cobol:
    cmds:
      - docker compose build cobol-server

  start:cobol:
    cmds:
      - docker compose up -d cobol-server

  re:cobol:
    deps: [build:cobol, start:cobol]

  # === mysql ===

  build:mysql:
    cmds:
      - echo "mysql uses image; no build needed"

  start:mysql:
    cmds:
      - docker compose up -d mysql

  re:mysql:
    deps: [start:mysql]
